---
- name: playbook for db setup
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    db_admin_user: root
    db_admin_pwd: root
    typo3_db_name: typo3
    typo3_db_user: typo3
    typo3_db_pwd: typo3
    wordpress_db_name: wordpress
    wordpress_db_user: wordpress
    wordpress_db_pwd: wordpress
  tasks:
    # root password for mysql-server
    - shell: echo "mysql-server-5.5 mysql-server/root_password_again password {{ db_admin_pwd }}" | debconf-set-selections
    - shell: echo "mysql-server-5.5 mysql-server/root_password password {{ db_admin_pwd }}" | debconf-set-selections
    - apt: name=mysql-server state=latest
      register: mysql-server_update
    - apt: name=mysql-client state=latest
    - apt: name=python-mysqldb state=latest
    - replace: dest=/etc/mysql/my.cnf regexp='(bind-address[^=]*=) 127.0.0.1' replace='\1 0.0.0.0'
    - service: name=mysql state=restarted
    
    # we want to activate phpmyadmin for apache... since we need to pipe, we use the "shell" module!
    - shell: echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
    - shell: echo "phpmyadmin phpmyadmin/mysql/admin-pass password {{ db_admin_pwd }}" | debconf-set-selections
    - apt: name=phpmyadmin
    - command: php5enmod mcrypt

    # typo3 db and user
    - name: create db
      mysql_db: name={{ typo3_db_name }} state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      register: typo3_db_create
    - name: user@localhost
      mysql_user: name={{ typo3_db_user }} password={{ typo3_db_pwd }} host=localhost priv={{ typo3_db_name }}.*:ALL state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      when: typo3_db_create.changed
    - name: user@%
      mysql_user: name={{ typo3_db_user }} password={{ typo3_db_pwd }} host="%" priv={{ typo3_db_name }}.*:ALL state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      when: typo3_db_create.changed
    - name: unzip import
      shell: gunzip --stdout --keep /vagrant/ansible/mysql/typo3.sql.gz > /tmp/typo3_mysql_data.sql
      when: typo3_db_create.changed
    - name: import data
      mysql_db: name={{ typo3_db_name }}  state=import login_user={{ db_admin_user }} login_password={{ db_admin_pwd }} target=/tmp/typo3_mysql_data.sql
      when: typo3_db_create.changed

    # wordpress db and user
    - name: create db
      mysql_db: name={{ wordpress_db_name }} state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      register: wordpress_db_create
    - name: debug wordpress_db_create
      debug: var=wordpress_db_create
    - name: user@localhost
      mysql_user: name={{ wordpress_db_user }} password={{ wordpress_db_pwd }} host=localhost priv={{ wordpress_db_name }}.*:ALL state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      when: wordpress_db_create.changed
    - name: user@%
      mysql_user: name={{ wordpress_db_user }} password={{ wordpress_db_pwd }} host="%" priv={{ wordpress_db_name }}.*:ALL state=present login_user={{ db_admin_user }} login_password={{ db_admin_pwd }}
      when: wordpress_db_create.changed
    - name: unzip import
      shell: gunzip --stdout --keep /vagrant/ansible/mysql/wordpress.sql.gz > /tmp/wordpress_mysql_data.sql
      when: wordpress_db_create.changed
    - name: import data
      mysql_db: name={{ wordpress_db_name }}  state=import login_user={{ db_admin_user }} login_password={{ db_admin_pwd }} target=/tmp/wordpress_mysql_data.sql
      when: wordpress_db_create.changed

  handlers:


